# Generated by Django 5.1.7 on 2025-04-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='pagamento',
            field=models.TextField(blank=True),
        ),
    ]
