# Generated by Django 5.1.7 on 2025-04-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='aniversario',
            field=models.CharField(help_text='Formato: DD/MM', max_length=5),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
